### ISSUE TITLE
CODE REVIEW: Rayhatron's Checkout Form

### ISSUE THREAD

**Issue by ry4-n** [VividCiphers/Daily-Tasks#14]
Please provide review on my Checkout form.  The review should include ways to improve the look and feel, the HTML code (semantically and syntactically ), CSS code, and any scripts.

Please refrain from saying things like, "I don't like this."  A better review would be to provide resources and examples of ways to do it better. 

Anyone is free to code review someone's work, but please add yourself as an Assignee to this issue.

**Comment by thinsoldier** [comment]
Made some improvements to the absolute positioning in this branch
https://github.com/VividCiphers/Daily-Tasks/tree/rayhatron-abspos

Redid all positioning via CSS Grid in this branch and made it properly responsive
https://github.com/VividCiphers/Daily-Tasks/tree/suggestions-for-rayhatron

![screen shot 2017-04-07 at 19 14 45](https://cloud.githubusercontent.com/assets/373834/24840468/f871f916-1d2a-11e7-9687-fa26328e64fb.png)
![screen shot 2017-04-07 at 19 34 02](https://cloud.githubusercontent.com/assets/373834/24840466/f86a98b0-1d2a-11e7-89f7-a6b925f1a407.png)
![screen shot 2017-04-07 at 19 55 27](https://cloud.githubusercontent.com/assets/373834/24840467/f86c2540-1d2a-11e7-850c-aef166265471.png)

There are lots of other improvements that can be done regarding classes over ids and more semantics.
