### ISSUE TITLE
CODE REVIEW: Vincent's Sign Up Form

### ISSUE THREAD

**Issue by ry4-n** [VividCiphers/Daily-Tasks#15]
Please provide review on my Sign Up form. The review should include ways to improve the look and feel, the HTML code (semantically and syntactically ), CSS code, and any scripts.

Please refrain from saying things like, "I don't like this." A better review would be to provide resources and examples of ways to do it better.

Anyone is free to code review someone's work, but please add yourself as an Assignee to this issue.

**Comment by thinsoldier** [comment]
I suggest adding @required to form inputs. Great job.
